client:
  default-uri: https://miportafoliouat.transunion.co/ws/UbicaPlusWebService/services/UbicaPlus?wsdl
  callback: http://dto.ubicaplus.webservice.com/ParametrosUbicaPlusDTO
  context-path: com.example.consumingwebservice.wsdl
  user:
    name: 307883
    password: Equidad2208*
logging:
  level:
    com.example.consumingwebservice: INFO
    org:
      springframework:
        ws: DEBUG
